// JavaScript Document
function cambia_provincia(){

var municipio_Antioquia=new Array("Abejorral", "Abriaquí", "Alejandría", "Amagá", "Amalfi", "Andes", "Angelopolis", "Angostura", "Anori", "Antioquia","Anza", "Apartado", "Arboletes", "Argelia", "Armenia", "Barbosa", "Belmira", "Bello", "Betania", "Betulia", "Bolívar", "Briceño", "Buritica", "Caceres", "Caicedo", "Caldas", "Campamento", "Cañasgordas", "Caracolí", "Caramanta", "Carepa", "Carmen de Viboral", "Carolina", "Caucasia", "Chigorodo", "Cisneros", "Cocorna", "Concepción", "Concordia", "Copacabana", "Dabeiba", "Don Matias", "Ebejico", "El Bagre", "Entrerrios", "Envigado", "Fredonia", "Frontino", "Giraldo", "Girardota", "Gómez Plata", "Granada", "Guadalupe", "Guarne", "Guatape", "Heliconia", "Hispania", "Itagui", "Ituango", "Jardín", "Jerico", "La Ceja", "La Estrella", "La Unión", "Liborina", "Maceo", "Marinilla", "Medellín", "Montebello", "Murindo", "Mutata", "Nari", "Necocli", "Nechi", "Olaya", "Peñol", "Peque", "Pueblorrico", "Puerto Berrio", "Puerto Nare", "Puerto Triunfo", "Remedios", "Retiro", "Rionegro", "Sabanalarga", "Sabaneta", "Salgar", "San Andrés", "San Carlos", "San Francisco", "San Jerónimo", "S. José", "La Monta",
"S.Juan De Urabá", "San Luis", "San Pedro", "San Pedro De Urabá", "San Rafael", "San Roque", "San Vicente", "Santa Barbara",
"Sta.Rosa D.Osos");
var municipio_Amazonas=new Array("C.D. Puerto Santander", "C.D. Tarapacá", "C.D. El Encanto", "C.D. La Chorrera", "C.D. La Pedrera", "C.D. Mirití-Paraná", "Leticia", "Puerto Nariño");
var municipio_Arauca=new Array("Arauca", "Arauquita", "Cravo Norte", "Fortul", "Puerto", "Rondón", "Saravena", "Tame");
var municipio_Atlantico=new Array("Barranquilla", "Baranoa", "Campo de la Cruz", "Candelaria", "Galapa", "Juan De Acosta", "Luruaco", "Malambo", "Manati", "Palmar D Varela", "Piojo", "Polonuevo", "Ponedera", "Puerto Colombia", "Repelón", "Sabanagrande", "Sabanalarga", "Santa Lucia", "Santo Tomas", "Soledad", "Suan", "Tubara", "Usiacuri");
var municipio_Bolivar=new Array("Achí", "Altos del Rosario", "Arenal", "Arjona", "Arroyohondo", "Barranco de Loba", "Cartagena", "Calamar", "Cantagallo", "Cicuco", "Clemencia", "Córdoba", "El Carmen de Bolívar","El Guamo", "El Peñón", "Hatillo de Loba", "Magangue", "Mahates", "Margarita", "Maria la Baja","Mompos", "Montecristo", "Morales", "Pinillos", "Regidor", "Río Viejo", "San Cristóbal", "San Estanislao", "San Fernando", "San Jacinto", "San Jacinto del Cauca", "San Juan Nepomuceno", "San Martín de Loba", "San Pablo", "Santa Catalina", "Santa Rosa", "Santa Rosa del Sur", "Simití", "Soplaviento", "Talaigua Nuevo", "Tiquisio", "Turbaco", "Turbaná", "Villanueva", "Zambrano");
var municipio_Boyaca=new Array("Almeida", "Aquitania", "Arcabuco", "Belén", "Berbeo", "Beteitiva", "Boavita", "Boyacá", "Briceño", "Buenavista", "Busbanza", "Caldas", "Campohermoso", "Cerinza", "Ciénega","Combita", "Coper", "Corrales", "Covarachia", "Cubara", "Cucaita", "Cuitiva", "Chinavita","Chiquinquirá", "Chiquiza", "Chiscas", "Chita", "Chitaraque", "Chivata", "Chivor", "Duitama", "El Cocuy", "El Espino", "Firavitoba", "Floresta", "Gachantiva", "Gameza", "Garagoa", "Guacamayas","Guateque", "Guayata", "Guican", "Iza", "Jenesano", "Jericó", "La Capilla", "La Uvita", "La Victoria", "Labranzagrande", "Leiva", "Macanal", "Maripi", "Miraflores", "Mongua", "Monguí", "Moniquirá",  "Motavita", "Muzo", "Nobsa", "Nuevo Colón", "Oicata", "Otanche", "Pachavita", "Páez", "Paipa","Pajarito", "Panqueba", "Pauna", "Paya", "Paz del Río", "Pesca", "Pisba", "Puerto Boyacá", "Quipama", "Ramiriquí", "Ráquira", "Rondón", "Saboya", "Sáchica", "Samacá", "San Eduardo", "San José de Pare", "San Luis de Gaceno", "San Mateo","San Miguel de Sema", "San Pablo de Borbur", "Santa Maria", "Santa Rosa de Viterbo", "Santa Sofía", "Santana","Sativanorte", "Sativasur", "Siachoque", "Soata", "Socota",  "Socha", "Sogamoso", "Somondoco", "Sora", "Soracá", "Sotaquirá", "Susacon", "Sutamarchán", "Sutatenza", "Tunja", "Tasco", "Tenza", "Tibaná", "Tibasosa", "Tinjacá", "Tipacoque", "Toca", "Toguí", "Topaga", "Tota", "Tunungua", "Turmequé", "Tuta", "Tutasa", "Umbita", "Ventaquemada", "Viracacha", "Zetaquira");
var municipio_Caldas=new Array("Chinchiná", "Marmato", "Pacora", "Salamina", "Villamaría", "Aguadas", "Filadelfia", "Marquetalia","Palestina", "Samana", "Viterbo",  "Anserma", "La Dorada", "Manizales", "Marulanda", "Pensilvania", "San Jose", "Aranzazu", "La Merced", "Neira",  "Riosucio", "Supía", "Belalcazar", "Manzanares", "Norcasia", "Risaralda", "Victoria");
var municipio_Caqueta=new Array("Florencia", "Albania", "Belén", "Andaquies", "Cartagena del Chaira", "Curillo", "El Doncello", "El Paujil", "La Montañita", "Milán", "Morelia", "Puerto Rico", "San José de Fragua", "San  Vicente del Caguan", "Solano", "Solita", "Valparaíso");
var municipio_Casanare=new Array("Aguazul", "Chameza", "Hato", "Corozal", "La Salina", "Maní", "Monterrey", "Nunchia", "Orocue", "Paz de Ariporo", "Pore", "Recetor",
"Sabanalarga", "Sacama", "San Luis de Palenque", "Tamara", "Tauramena", "Trinidad", "Yopal", "Villanueva");
var municipio_Cauca=new Array("Florencia", "La Sierra", "Miranda", "Patia(El Bordo)", "Purace", "Santa Rosa", "Sucre", "Totoro",		
"Páez", "Puerto", "Tejada", "Santander de Quilichao", "Suárez", "Toribio", "Balboa", "Caldono",		
"Popayán", "Bolívar", "Caloto", "Guapi", "La Vega", "Morales", "Piamonte", "Rosas Silvia", "Timbío",		
"San Sebastián", "Sotara", "Timbiquí", "Argelia", "Cajibio", "El Tambo", "Jambaló", "Mercaderes",		
"Villa Rica", "Almaguer", "Buenos Aires", "Corinto", "Inza", "López Padilla", "Piendamo")
var municipio_Cesar=new Array("Aguachica", "Chimichagua", "Gamarra", "Pailitas", "San Alberto", "Agustín Codazzi", "Chiriguaná", "González", "Pelaya", "San Diego", "Astrea", "Curumaní", "La Gloria", "Pueblo Bello",	"San Martín", "Becerril", "El Copey", "La Jagua", "Ibirico", "Río De Oro", "Tamalameque", "Valledupar", "Bosconia", "El Paso", "Manaure", "Balcón Del Cesar", "Robles (La Paz)");
var municipio_Choco=new Array("Acandi", "Bajo baudo", "Certegui", "Lloro", "Nuqui", "Sipi", "Alto baudo", "Canton de san pablo", "Istmina", "Medio san juan", "Riosucio", "Unión panamericana", "El carmen", "Medio baudo", "Rio quito", "Unguia", "Bagado", "Litoral del san juan", "Condoto", "Medio atrato", "Rio iro", "Tado", "Atrato", "Bojaya", "Quibdo", "Bahia solano", "Carmen del darien", "Jurado", "Novita", "San jose del palmar");
var municipio_Cordoba=new Array("Ayapel", "Buenavista", "Canalete", "Cereté", "Chima", "Chinú", "Cienaga De Oro", "Cotorra", "La Apartada", "Lorica", "Los Córdobas", "Montería", "Momil", "Montelíbano", "Moñitos", "Planeta Rica", "Pueblo Nuevo", "Puerto Escondido", "Puerto Libertador", "Purísima","Sahagún", "San Andrés", "Sotavento", "San Antero", "San Bernardo", "Viento", "San Carlos", "San Pelayo", "Tierralta", "Valencia");
var municipio_Cundinamarca=new Array("Agua de Dios", "Alban", "Anapoima", "Anolaima", "Arbelaez", "Beltrán", "Bituima", "Bogota", "Bojacá", "Cabrera", "Cachipay", "Cajicá", "Caparrapí", "Caqueza", "Carmen de Carupa", "Chaguaní", "Chia", "Chipaque", "Choachí", "Chocontá", "Cogua", "Cota", "Cucunubá", "El Colegio", "El Peñón", "El Rosal1" ,"Facatativa", "Fómeque", "Fosca", "Funza", "Fúquene", "Fusagasuga", "Gachalá", "Gachancipá", "Gacheta", "Gama", "Girardot", "Granada2", "Guachetá", "Guaduas", "Guasca", "Guataquí", "Guatavita", "Guayabal de Siquima", "Guayabetal", "Gutiérrez", "Jerusalén", "Junín", "La Calera", "La Mesa", "La Palma", "La Peña", "La Vega", "Lenguazaque", "Machetá", "Madrid", "Manta", "Medina", "Mosquera", "Nariño", "Nemocón", "Nilo", "Nimaima", "Nocaima", "Ospina", "Pérez", "Pacho", "Paime", "Pandi", "Paratebueno", "Pasca", "Puerto", "Salgar", "Pulí", "Quebradanegra", "Quetame", "Quipile", "Rafael", "Reyes", "Ricaurte", "San Bernardo", "San Cayetano", "San Francisco", "San Juan de Rioseco", "San  Antonio del  Tequendama", "Sasaima", "Sesquilé", "Sibaté", "Silvania", "Simijaca", "Soacha", "Sopo", "Subachoque", "Suesca", "Supatá", "Susa", "Sutatausa", "Tabio", "Tausa", "Tena", "Tenjo", "Tibacuy", "Tibirita", "Tocaima", "Tocancipá" ,"Topaipí", "Ubalá", "Ubaque", "Ubaté", "Une", "Utica", "Vergara", "Viani", "Villagomez", "Villapinzón", "Villeta", "Viota", "Yacopí", "Zipacón", "Zipaquirá");
var municipio_Guainia=new Array("Inírida", "Barranco", "Minas", "Cacagual", "La Guadalupe", "Morichal Nuevo", "Pana Pana", "Puerto Colombia", "San Felipe");
var municipio_Guaviare=new Array("San José del Guaviare", "ciudad capital", "Calamar", "El Retorno", "Miraflores");
var municipio_Guajira=new Array("Riohacha", "Albania", "Barrancas", "Dibulla", "Distraccion", "El Molino","Fonseca", "Hatonuevo", "La Jagua del Pilar", "Maicao", "Manaure", "San Juan del Cesar", "Uribia", "Urumita", "Villanueva");
var municipio_Huila=new Array("Neiva", "Acevedo", "Agrado", "Aipe", "Algeciras", "Altamira", "Baraya", "Campoalegre", "Colombia", "Elias", "Garzón", "Gigante", "Guadalupe", "Hobo", "Iquira", "Isnos", "La Argentina", "La Plata", "Nataga", "Oporapa", "Paicol", "Palermo", "Palestina", "Pital", "Pitalito", "Rivera", "Saladoblanco", "San Agustín", "Santa Maria",	"Suaza", "Tarqui", "Tesalia", "Tello", "Teruel", "Timana", "Villavieja", "Yaguara");
var municipio_Magdalena=new Array("Santa Marta", "Algarrobo", "Aracataca", "Ariguani", "Cerro San Antonio","Chivolo", "Cienaga", "Concordia", "El Piñon", "El Reten", "Fundacion", "Guamal", "Nueva Granada", "Pedraza", "Pijiño Del Carmen", "Pivijay", "Plato", "Puebloviejo", "Remolino", "Sabanas De San Angel", "Santa Barbara De Pinto", "San Sebastian De Buenavista", "San Zenon", "Santa Ana", "Salamina", "Sitionuevo", "Tenerife", "Zapayan", "Zona", "Bananera");
var municipio_Meta=new Array("Villavicencio", "Acacias", "Barranca de Upia", "Cabuyaro", "Castilla", "La Nueva", "Cubarral", "Cumaral", "El Calvario", "El Castillo", "El Dorado", "Fuente de Oro", "Granada",	"Guamal", "Mapiripán", "Mesetas", "La Macarena", "La Uribe", "Lejanías", "Puerto Concordia", "Puerto Gaitán", "Puerto López", "Puerto", "Lleras", "Puerto Rico", "Restrepo", "San Carlos", "Guaroa", "San Juan de Arama", "San Juanito", "San Martín", "Vista Hermosa");
var municipio_Narino=new Array("Pasto", "Alban", "Aldaña", "Ancuya", "Arboleda", "Barbacoas", "Belen","Buesaco", "Colon(genova)", "Consaca", "Contadero", "Cordoba", "Cuaspud", "Cumbal", "Cumbitara", "Chachagui", "El charco", "El peñol","El rosario", "El tablon", "El tambo", "Funes", "Guachucal", "Guaitarilla", "Gualmatan", "Iles", "Imues", "Ipiales", "La cruz", "La florida", "La llanada",	"La tola", "La union", "Leiva", "Linares", "Los andes", "Magui", "Mallama", "Mosquera",	"Nariño", "Olaya herrera", "Ospina",	 "Pizarro", "Policarpa", "Potosi", "Providencia", "Puerres", "Pupiales", "Ricaurte", "Roberto payan", "Samaniego", "Sandona", "San bernardo",  "San lorenzo", "San pablo", "San pedro de cartago", "Santa barbara", "Santacruz", "Sapuyes", "Taminango", "Tangua",	"Tumaco","Tuquerres", "Yacuanquer");
var municipio_Norte_de_Santander=new Array("Cúcuta", "Abrego", "Arboledas", "Bochalema", "Bucarasica", "Cácota", "Cáchira", "Chinácota", "Chitagá", "Convención", "Cucutilla", "Durania", "El Carmen", "El Tarra", "El Zulia", "Gramalote", "Hacari", "Herrán", "Labateca", "La Esperanza", "La Playa", "Los Patios","Lourdes", "Mutiscua", "Ocaña", "Pamplona", "Pamplonita", "Puerto Santander",	"Ragonvalia", "Salazar", "San Calixto", "San Cayetano", "Santiago", "Sardinata", "Silos", "Teorama", "Tibú", "Toledo", "Villacaro", "Villa del Rosario");
var municipio_Putumayo=new Array("Colón", "Mocoa", "Orito", "Puerto", "Asís", "Puerto Caycedo", "Puerto Guzmán", "Puerto Leguízamo", "San Francisco", "San Miguel", "Santiago", "Sibundoy", "Valle del Guamuez", "Villagarzón");
var municipio_Quindio=new Array("Armenia", "Buenavista", "Calarcá", "Circasia", "Córdoba", "Filandia", "Génova", "La Tebaida", "Montenegro", "Pijao", "Quimbaya", "Salento");
var municipio_Risaralda=new Array("Pereira", "Apia Balboa", "Belén de Umbría", "Dos Quebradas", "Guatica", "La Celia", "La Virginia", "Marsella", "Mistrato", "Pueblo Rico", "Quinchía", "Santa Rosa de Cabal", "Santuario");
var municipio_San_Andres=new Array("San Andrés", "Providencia", "Santa Catalina", "Alicia", "Serrana","Serranilla", "Quitasueño", "Alburquerque", "Roncador", "East South East", "Blowing Rocks", "Cangrejo", "Casabaja", "Córdoba", "Valle", "Hermanos", "Rocoso", "Rosa", "Santander", "Sucre");
var municipio_Santander=new Array("Bucaramanga", "Aguada", "Albania", "Aratoca", "Barbosa","Barichara", "Barrancabermeja", "Betulia", "Bolívar", "Cabrera", "California", "Capitanejo", "Carcasi", "Cepita","Cerrito", "Charalá", "Charta", "Chima", "Chipatá", "Cimitarra", "Concepción", "Confines", "Contratación", "Coromoro", "Curití", "El Carmen", "El Guacamayo", "El Peñón", "El Playón", "Encino","Enciso", "Florián", "Floridablanca", "Galán", "Gambita", "Girón", "Guaca", "Guadalupe", "Guapota","Guavatá", "Guepsa", "Hato", "Jesús Maria", "Jordán", "La Belleza", "Landazuri", "La Paz", "Lebrija", "Los Santos", "Macaravita", "Málaga", "Matanza", "Mogotes", "Molagavita", "Ocamonte", "Oiba", "Onzaga", "Palmar", "Palmas del Socorro", "Páramo", "Piedecuesta", "Pinchote", "Puente Nacional", "Puerto Parra", "Puerto Wilches", "Rionegro", "Sabana de Torres", "San Andrés", "San Benito", "San Gil", "San Joaquín", "San José de Miranda", "San Miguel", "San Vicente de Chucurí", "Santa Bárbara", "Santa Helena", "Simacota", "Socorro", "Suaita", "Sucre", "Surata", "Tona", "Valle", "San José", "Vélez",  "Vetas", "Villanueva", "Zapatoca");
var municipio_Sucre=new Array("Sincelejo", "Buenavista", "Caimito", "Coloso", "Corozal", "Chalán", "El Roble", "Galeras", "Guaranda", "La Unión", "Los Palmitos", "Majagual", "Morroa", "Ovejas", "Palmito", "Sampues", "San Benito", "Abad", "San Juan De Betulia", "San Marcos", "San Onofre", "San Pedro", "Sincé", "Sucre", "Tolú", "Toluviejo");
var municipio_Tolima=new Array("Ibagué", "Alpujarra", "Alvarado", "Ambalema", "Anzoategui", "Armero", "Ataco", "Cajamarca", "Carmen de Apicalá", "Casabianca", "Chaparral", "Coello", "Coyaima", "Cunday", "Dolores", "Espinal", "Falán", "Flandes", "Fresno", "Guamo", "Herveo", "Honda", "Icononzo", "Lérida","Líbano", "Mariquita", "Melgar", "Murillo" ,"Natagaima", "Ortega", "Palocabildo", "Piedras",  "Planadas", "Prado", "Purificación", "Rioblanco", "Roncesvalles", "Rovira", "Saldaña", "San Antonio", "San Luis", "Santa Isabel", "Suárez", "Valle de San Juan", "Venadillo", "Villahermosa", "Villarrica");
var municipio_Valle_del_Cauca=new Array("Cali", "Alcalá", "Andalucía", "Ansermanuevo", "Argelia", "Bolívar","Buenaventura", "Buga", "Bugalagrande", "Caicedonia", "Calima (Darien)", "Candelaria", "Cartago","Dagua", "El Aguila", "El Cairo", "El Cerrito", "El Dovio", "Florida", "Ginebra", "Guacari", "Jamundí", "La Cumbre", "La Unión", "La Victoria", "Obando", "Palmira", "Pradera", "Restrepo", "Riofrío","Roldanillo", "San Pedro", "Sevilla", "Toro", "Trujillo", "Tulúa", "Ulloa", "Versalles", "Vijes",  "Yotoco", "Yumbo", "Zarzal");
var municipio_Vaupes=new Array("Mitú","CarurúTaraira", "Pacoa", "Papunaua", "Yavaraté", "Acaricuara","Villafátima");
var municipio_Vichada=new Array("Puerto Carreño", "La Primavera", "Santa RosalíaCumaribo");

 
//tomo el valor del select del departamento  elegido
var departamento
departamento = document.menu.departamento[document.menu.departamento.selectedIndex].value
//miro a ver si el departamento está definido
if (departamento!= 0) {
//si estaba definido, entonces coloco las opciones de la ciudad correspondiente.
//selecciono el array de ciudad adecuado
mis_municipio=eval("municipio_" + departamento)
//calculo el numero de ciudad
num_municipio = mis_municipio.length
//marco el número de ciudad en el select
document.menu.municipio.length = num_municipio
//para cada ciudad del array, la introduzco en el select
for(i=0;i<num_municipio;i++){
document.menu.municipio.options[i].value=mis_municipio[i]
document.menu.municipio.options[i].text=mis_municipio[i]
}
}else{
//si no había ciudad seleccionada, elimino las provincias del select
document.menu.municipio.length = 1
//coloco un guión en la única opción que he dejado
document.menu.municipio.options[0].value = "-"
document.menu.municipio.options[0].text = "-"
}
//marco como seleccionada la opción primera de ciudad
document.menu.municipio.options[0].selected = true
}

 